name: Build and Deploy
on:
  push:
    branches:
      - new_dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ secrets.FRANKLIN }}
        branch: master # The branch the action should deploy to.
        folder: __site # The folder the action should deploy.