name: Build and Deploy
on:
  push:
    branches:
      - new_dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        ACCESS_TOKEN: ${{ secrets.FRANKLIN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: __site # The folder the action should deploy.